name: Build

on:
  push:
    branches: [ 210227-cicr-reset-test ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
        
    - name: Restore NuGet packages
      run: nuget restore FS2020PlanePath.sln

    - name: Build the solution
      run: msbuild FS2020PlanePath.sln /p:Configuration=Release

    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        name: MSFS2020-PilotPathRecorder-n2
        path: FS2020PlanePath/bin/
        retention-days: 30
