name: Build

on:
  push:
    branches: [ 210227-cicr ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

#    - name: Install .NET Core
#      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: 5.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
        
    - name: Restore NuGet packages
      run: nuget restore FS2020PlanePath.sln

    - name: Build the solution
      run: msbuild FS2020PlanePath.sln /p:Configuration=Release /p:PackageAsSingleFile=true
      
#    - name: Execute unit tests
#      run: dotnet test FS2020PlanePath.XUnitTests/FS2020PlanePath.XUnitTests.csproj --no-restore
      
#    - name: Publish artifacts
#      uses: actions/upload-artifact@v1
#      with:
#        name: Installer
#        path: bin\Release\Publish

    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        name: Deliverable
        path: |
          MSFS2020-PilotPathRecorder\MSFS2020-PilotPathRecorder\FS2020PlanePath\bin\Release\app.publish\FS2020PlanePath.exe
          MSFS2020-PilotPathRecorder\FS2020PlanePath\bin\Release\app.publish\FS2020PlanePath.exe
          FS2020PlanePath\bin\Release\app.publish\FS2020PlanePath.exe
          bin\Release\app.publish\FS2020PlanePath.exe
          Release\app.publish\FS2020PlanePath.exe
          app.publish\FS2020PlanePath.exe
          FS2020PlanePath.exe
        retention-days: 30

